# Site settings
title: Will's Site
email: wgpierce01 at gmail.com
description: >
  Will's Site
baseurl: ""
url: "http://wgpierce.github.io"
github_username: wgpierce
resume: /resources/William Pierce Resume.pdf
collections:
    projects:
        output: true

# Build settings
markdown: kramdown
